### ISSUE TITLE
"tie" causes error when the input data contain redundant actors

### ISSUE THREAD

**Issue by SNAnalyst** [TilburgNetworkGroup/remstats#29]
When the input dataframe for `tie `contains actors that are not present in the `reh` object (or in the `actors` argument), `tomstats` throws an (obscure) error.  Rather, the desired behavior is that `tie` should juist discard these "redundant" actors and build the tie statistic without them. 

Of course, if a required actor (ie. an actor that occurs inside `reh` or is specified in the `actors` argument) is missing from the input dataframe `x`, an informative error should be thrown. I haven't tested this scenario yet.  But otherwise, it should just work, even when redundant actors are present in the input.

Note that `receive` and `send` do work correctly when redundant actors are in their input dataframe.

(I only used `tomstats`, so I do not know if this is an issue in `aomstats` as well)

**Comment by mlmeijerink** [comment]
Fixed in remstats V3.0.0 (currently only available on the branch new_remify).
