### ISSUE TITLE
message when redundant actors are present in input data

### ISSUE THREAD

**Issue by SNAnalyst** [TilburgNetworkGroup/remstats#30]
In `tomstats`, when the input dataframe for `receive` or `send` contains redundant actors (ie. actors that are not present in the `reh` object or in the `actors` argument), it would be nice to the user to print a message that states that there are actors in the input data that are not present in `reh` or `actors` and have been discarded in the calculation of the statistics.

When `tie` has been fixed to not cause an error  in this situation, such a message should also be generated by `tie`.

Note: I only used `tomstats`, but this should also happen in `aomstats` .

**Comment by mlmeijerink** [comment]
Fixed in remstats V3.0.0 (currently only available on the branch new_remify).
