### ISSUE TITLE
simply add a new statistic

### ISSUE THREAD

**Issue by SNAnalyst** [TilburgNetworkGroup/remstats#31]
Imagine the situation where aomstats is run as `statistix <- aomstats(bunch of stats)`. 
When running several models, it often happens that the researcher realizes that an additional statistic would be useful in the model that wasn't part of the `statistix` object.
Although it would be possible to run `statistix2 <- aomstats(bunch of stats, including the new one)`, this would be a waste of time since all of the other statistics were already computed as part of `statistix`.

It would be great if it would be possible to just calculate the new statistic and add that to the `statistix` object. 
So, either:

```
extrastat <- aomstats(new_stat)
statistix2 <- append(statistix, extrastat)
```

or, in one go:

`statistix2 <- aomstats(new_stat, add_to = statistix)`
where the argument `add_to` adds the new stat to the `statistix` object.

**Comment by mlmeijerink** [comment]
This will be available in the next update with the function bind_remstats() that takes as argument two or more remstats objects that are combined into one.
