### ISSUE TITLE
fix "partial match"

### ISSUE THREAD

**Issue by SNAnalyst** [TilburgNetworkGroup/remstats#35]
Every time I run `remstats`, I receive the warning of partial matches to `factors`.  
This probably does not affect the accuracy of the function, but partial matches are less safe than exact matches. Please make sure to not use any partial matches in the code.

Here is an example:

```
stats_rem <- remstats::tomstats(~
....                                   inertia(scaling = "prop") # FrPSndSnd
....                                 , edgelist = reh)
Warning message:
In attr(ft, "factor") : partial match of 'factor' to 'factors'

```

**Comment by mlmeijerink** [comment]
Hi, this will be fixed in the next version!
