### ISSUE TITLE
option: add progress bar when running aomstats and tomstats

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remstats#38]
Hi, maybe it would be good to add a progress bar to give users an indication how long it takes, e.g., using the 'txtProgressBar' function where the progress is based on the event index.

**Comment by mlmeijerink** [comment]
Hi, good idea to add a progress bar. However, remstats does not loop over events but over statistics. Therefore, I think it would be only useful for models with a larger number of statistics.

**Comment by mlmeijerink** [comment]
This was implemented in `remstats v3.1.1`. A progress bar can be obtained by setting the `display_progress` argument equal to `TRUE`.
