### ISSUE TITLE
oamstats$edgelist shows dyad indicator

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remstats#42]
When computing remstats for a oam then oamstats$edgelist shows dyads as observations which is strange given the nature of the aom. Rather it should contain the sender and receiver. I also submitted this to remify. Giuseppe was planning to update this. So maybe you are already informed.

**Comment by mlmeijerink** [comment]
The output from remstats no longer gives the edgelist (it stays at remify). Therefore this issue is fixed/no longer relevant.
