### ISSUE TITLE
Character/factor type of exogenous covariate

### ISSUE THREAD

**Issue by reck0ner** [TilburgNetworkGroup/remstats#57]
It would be benificial for remstats to work with character and factor types for exogenous covariates of actors or dyads

**Comment by mlmeijerink** [comment]
Fixed in remstats v.3.2.0 (on CRAN). 

Note: this does not always make sense, e.g., what is the mean of a character or factor variable? It is fixed when it makes sense (e.g., the "same" effect) and outputs an informative error in other instances.
